apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      tag: {{ .Values.tag }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        tag: {{ .Values.tag }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: '{{ .Values.image }}:{{ .Values.tag }}'
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 5